services:
  server:
    image: quickgraph-server
    build:
     context: ./server
     dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

  client:
    image: quickgraph-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      # - docs
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  # docs:
  #   build:
  #     context: ./docs
  #   ports:
  #     - "4000:4000"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
