services:
  server:
    image: quickgraph-server
    build:
     context: ./server
     dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - MONGODB__DATABASE_NAME=quickgraph
      - MONGODB__URI=mongodb://root:example@mongodb:27017
      - AUTH__SECRET_KEY=example

  client:
    image: quickgraph-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      - docs
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_DOC_BASE_URL=http://localhost:4000

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - static_img:/app/static/img
    networks:
      - app-network
    depends_on:
      - init-static-img

  init-static-img:
    image: curlimages/curl:latest
    volumes:
      - static_img:/static_img
    command: >
      sh -c '
      cd /static_img &&
      curl -L https://nlp-tlp.s3.ap-southeast-2.amazonaws.com/static-img.tar.gz | tar xz --strip-components=3 &&
      touch .initialized
      '

volumes:
  mongodb_data:
  static_img:

networks:
  app-network:
    driver: bridge
